---

- hosts: "all"
  vars:
    _timeout: 5
    _host: "google.com"
  roles:
    - role: "ansible-pdns-recursor"
      tags:
        - "pdns-recursor"
  post_tasks:
    - block:
        - include: "tests/test_dns_resolving.yml"
      tags:
        - "tests"
