---

- name: fail unless we run on a supported distribution
  fail: >
    msg="Unfortunately, the 'pdns_recursor'-role is not supported on {{ ansible_distribution_release }}! :-("
  when: ansible_distribution_release|lower not in pdns_recursor_prerequisites_supported_distribution_releases

- name: add additional repositories
  apt_repository: >
    repo="{{ item }}"
    state="{{ pdns_recursor_prerequisites_apt_repository_state }}"
  with_items:
    - "{{ pdns_recursor_prerequisites_apt_repository_repo_list }}"
